---
title: "The tmap book style"
author: "Martijn Tennekes, Jakub Nowosad"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Text

- Use one line per sentence during development for ease of tracking changes
- Leave a single empty line space before and after each code chunk
- Format content as follows: 
    - **package_name**
    - `class_of_object`
    - `function_name()`
- Spelling: use `en-us`

# Code

- `library(package)` - library without quotes
- `=` - assignment operator (instead of `<-`)
- ` = ` , ` > `, etc. - spaces around operators
- `"text"` - double quotes for character values
- `for(i in 1:9) {print(i)}` - use space separation for curly brackets
- When indenting your code, use two spaces (tab in RStudio)
- When using pipes, pipe the first object (`x %>% fun() %>% ...` not `fun(x) %>% ...`)

# Comments

Comment your code unless obvious because the aim is teaching.
Use capital first letter for full-line comment:

```r
# Create object x
x = 1:9
```

Do not capitalise comment for end-of-line comment:

```r
y = x^2 # square of x
```

# Captions

Captions should not contain any markdown characters, e.g. `*` or `_`. 
References in captions also should be avoided.

# Figures

Names of the figures should contain a chapter number, e.g. `04-world-map.png` or `11-population-animation.gif`.

# File names

- Minimize capitalization: use `file-name.rds` not `file-name.Rds`
- `-` not `_`: use `file-name.rds` not `file_name.rds`

# References

Zotero?

# More information

- https://bookdown.org/yihui/bookdown/
- https://bookdown.org/yihui/rmarkdown/books.html