---
title: "tmap4: aesthetics"
author: Jakub Nowosad
date: 2020-11-30
output: 
  html_document: 
    toc: yes
    number_sections: yes
    keep_md: yes
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tibble)
library(glue)
library(dplyr)

aes_df = tribble(
  ~aes_name, ~layer,
  "fill", "tm_polygons()",
  "fill", "tm_symbols()",
  #"fill", "tm_raster()",
  #"fill", "tm_text()",
  "fill", "tm_fill()",
  "fill", "tm_bubbles()",
  #"fill", "tm_dots()",
  #?"fill", "tm_markers()",
  "fill", "tm_square()",
  #"fill", "tm_iso()",
  #"fill", "tm_rgb()/tm_rgba()",
  "color", "tm_polygons()",
  "color", "tm_symbols()",
  "color", "tm_lines()",
  "color", "tm_raster()",
  "color", "tm_text()",
  "color", "tm_borders()",
  "color", "tm_bubbles()",
  "color", "tm_dots()",
  "color", "tm_markers()",
  "color", "tm_square()",
  "color?", "tm_iso()",
  "color", "tm_rgb()/tm_rgba()",
  "stroke", "tm_polygons()",
  "size", "tm_symbols()",
  "stroke", "tm_lines()",
  # "size", "tm_raster()",
  "size", "tm_text()",
  "stroke", "tm_borders()",
  "size", "tm_bubbles()",
  "size", "tm_dots()",
  "size", "tm_markers()",
  "size", "tm_square()",
  "size?", "tm_iso()",
  "linetype", "tm_polygons()",
  "shape", "tm_symbols()",
  "linetype", "tm_lines()",
  # "shape", "tm_raster()",
  "shape", "tm_text()",
  "linetype", "tm_borders()",
  "shape", "tm_bubbles()",
  "shape", "tm_dots()",
  "shape", "tm_markers()",
  "shape", "tm_square()",
  "linetype?", "tm_iso()",
  "stroke", "tm_symbols()",
  "stroke", "tm_bubbles()",
  "stroke", "tm_markers()",
  "stroke", "tm_square()",
  "text", "tm_text()",
  "text?", "tm_iso()",
  "stroke?", "tm_iso()"
)
```

```{r, echo=FALSE}
other_data_aes_df = tribble(
  ~other_data_aes_name, ~layer,
  "alpha", "tm_polygons()",
  "alpha", "tm_symbols()",
  "alpha", "tm_raster()",
  "alpha", "tm_text()",
  "alpha", "tm_fill()",
  "alpha", "tm_bubbles()",
  "alpha", "tm_dots()",
  "alpha", "tm_markers()",
  "alpha", "tm_square()",
  "alpha", "tm_iso()",
  "alpha", "tm_rgb()/tm_rgba()",
  "alpha", "tm_lines()",
  "alpha", "tm_borders()"
  )
```

```{r, echo=FALSE}
# other_aes_df = tribble(
#   ~other_aes_name, ~layer,
#   "colorNA", "tm_polygons()",
#   "colorNULL", "tm_polygons()",
#   "scale", "tm_symbols()",
#   "perceptual", "tm_symbols()",
#   "size.max", "tm_symbols()",
#   "size.lim", "tm_symbols()",
#   "colorNA", "tm_symbols()",
#   "colorNULL", "tm_symbols()",  
#   "shapeNA", "tm_symbols()",
#   "jitter", "tm_symbols()",
#   "xmod", "tm_symbols()",
#   "ymod", "tm_symbols()",
#   "icon.scale", "tm_symbols()",
#   "alpha", "tm_raster()",
#   "alpha", "tm_text()",
#   "alpha", "tm_fill()",
#   "alpha", "tm_bubbles()",
#   "alpha", "tm_dots()",
#   "alpha", "tm_square()",
#   "alpha", "tm_iso()",
#   "alpha", "tm_rgb()/tm_rgba()"
#   )
```

```{r}
what_aes = function(layer_name){
  aes = filter(aes_df, layer == layer_name)
  aes_txt = glue_collapse(aes$aes_name, sep = ", ")
  glue("{aes_txt}")
}
what_other_aes = function(layer_name){
  aes = filter(other_data_aes_df, layer == layer_name)
  aes_txt = glue_collapse(aes$other_data_aes_name, sep = ", ")
  glue("{aes_txt}")
}
aes_df2 = tibble(layer = unique(aes_df$layer))
aes_df2$aes = purrr::map_chr(aes_df2$layer, what_aes)
aes_data_df2 = tibble(layer = unique(other_data_aes_df$layer))
aes_data_df2$other_aes = purrr::map_chr(aes_data_df2$layer, what_other_aes)

all_df = left_join(aes_df2, aes_data_df2)
```


# Layers and aesthetics list

```{r, echo=FALSE}
knitr::kable(all_df, caption = "Map layers and their aesthetics that use data variables")
```

# Questions/comments

1. Do we assume (similarly to ggplot2) that `alpha` relates to all aspects of visualization (e.g., fill and borders in `tm_polygons()`)?
