# Layers {#layers}

```{r, echo=FALSE}
layers_basic_df = tibble::tribble(
  ~Function, ~Element, ~Geometry,
  "tm_polygons()", "polygons (borders and fill)", "polygons",
  "tm_symbols()", "symbols", "points, polygons, and lines", 
  "tm_lines()", "lines", "lines", 
  "tm_raster()", "raster", "raster",
  "tm_text()", "text", "points, polygons, and lines"
)
layers_extended_df = tibble::tribble(
  ~Function, ~Element, ~Geometry,
  "tm_borders()", "polygons (borders)", "polygons",
  "tm_fill()", "polygons (fill)", "polygons",
  "tm_bubbles()", "bubbles", "points, polygons, and lines",
  "tm_dots()", "dots", "points, polygons, and lines",
  "tm_markers()", "marker symbols", "points, polygons, and lines",
  "tm_square()", "squares", "points, polygons, and lines",
  "tm_iso()", "lines with text labels", "lines",
  "tm_rgb()/tm_rgba()", "raster (RGB image)", "raster"
)
layers_df = rbind(layers_basic_df, 
                  layers_extended_df)
```

\@ref(tab:layers-table)

```{r layers-table, echo=FALSE, warning=FALSE}
library(magrittr)
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
knitr::kable(layers_df, 
             caption = "Map layers.",
             caption.short = "Map layers.",
             booktabs = TRUE) %>%
  kableExtra::kable_styling("striped",
                            latex_options = "striped", 
                            full_width = FALSE) %>% 
  kableExtra::column_spec(1, bold = TRUE, monospace = TRUE) %>% 
  kableExtra::pack_rows("Basic functions", 1, 5) %>%
  kableExtra::pack_rows("Derived functions", 6, 13)
```

## Color palettes <!--JN: I am not sure where this section should go-->




```{r palette-types, fig.cap="Examples of three main types of color palettes: categorical, sequential, and diverging", echo=FALSE}
# y - a named list of palettes
plot_palette_types = function(y){
  
  my_n = length(y[[1]])
  n_colors = length(y)
  ylim = c(0, n_colors)
  
  oldpar = par(mgp = c(2, 0.25, 0))
  on.exit(par(oldpar))
  plot(
    1,
    1,
    xlim = c(0, max(my_n)),
    ylim = ylim,
    type = "n",
    axes = FALSE,
    bty = "n",
    xlab = "",
    ylab = ""
  )
  
  for (i in seq_len(n_colors)) {
    rect(
      xleft = 0:(my_n - 1),
      ybottom = i - 1,
      xright = 1:my_n,
      ytop = i - 0.2,
      col = y[[i]],
      border = "light grey"
    )
  }
  text(
    rep(0, n_colors),
    (1:n_colors) - 0.6,
    labels = paste(names(y), " "),
    xpd = TRUE,
    adj = 1
  )
}
# JN: probably this figure should use the default tmap color palettes
p_cat = hcl.colors(7, "Set3")
p_seq = hcl.colors(7, "YlOrBr")
p_div = hcl.colors(7, "RdYlGn")
# p_vir = 
y = list(Diverging = p_div, Sequential = p_seq, Categorical = p_cat)
plot_palette_types(y)
```


<!-- three main types of color palettes -->
<!-- categorical -->
<!-- https://developer.r-project.org/Blog/public/2019/11/21/a-new-palette-for-r/index.html -->
<!-- sequential -->

<!-- diverging -->
<!-- mention midpoint -->

<!-- black and white (also in contrast to the three main palettes types)-->
<!-- color blindness -->
<!-- palette properties -->
<!-- anti-rainbow -->



<!-- three ways to set colors in tmap: -->
<!-- 1. vector of colors (names vs hex) -->
<!-- 2. palette functions (e.g. RColorBrewer, rcartocolor, grDevices::hcl.colors) -->
<!-- 3. build-in names in tmap <!-- tmaptools::palette_explorer() --> -->
<!-- <!-- including viridis --> -->
<!-- also the `n` argument -->
<!-- also the `-` sign -->
<!-- The type of palette from aes.palette is automatically determined, but can be overwritten: use "seq" for sequential, "div" for diverging, and "cat" for categorical. -->
<!-- alpha? -->

<!-- resources: -->
<!-- - colorspace -->
<!-- - Polychrome -->
<!-- - https://bookdown.org/hneth/ds4psy/D-2-apx-colors-essentials.html -->
<!-- - https://developer.r-project.org/Blog/public/2019/11/21/a-new-palette-for-r/index.html -->

## The color scale styles <!--JN: I am not sure where this section should go-->

```{r}
# replace this data with some new tmap dataset
library(sf)
library(tmap)
file_path = system.file("shapes/world.gpkg", package = "spData")
world = read_sf(file_path)
world_moll = st_transform(world, crs = "+proj=moll")
```

<!-- one plot with five panels: one color/adjacent polygons/categorical/discrete/continuous? -->
<!-- or maybe start with one color/adjacent polygons -->
<!-- and next present three main types of color palettes -->
<!-- after that categorical/discrete/continuous?? -->

```{r}
tm_one = tm_shape(world_moll) +
  tm_polygons(col = "lightblue")
tm_uni = tm_shape(world_moll) +
  tm_polygons(col = "MAP_COLORS")
```


To see and compare examples of every color scale style from **tmap** visit https://geocompr.github.io/post/2019/tmap-color-scales/.
