# Layout {#layout}

## Typography

<!-- Font faces and font families -->



<!-- where to put the font section ?? -->
<!-- intro -->
<!-- font faces and font families -->

@guidero_typography_2017

```{r, echo=FALSE}
library(tmap)
data("World")
bf = c("plain", "italic", "bold", "bold.italic")
tm_shape(World) +
  tm_borders(alpha = 0) +
  tm_credits("plain", fontface = "plain", position = c("center", "center"),
             size = 2) +
  tm_credits("italic", fontface = "italic", position = c("center", "center"),
             size = 2) +
  tm_credits("bold", fontface = "bold", position = c("center", "center"),
             size = 2) +
  tm_credits("bold.italic", fontface = "bold.italic", position = c("center", "center"),
             size = 2) +
  tm_layout(frame = FALSE)
```

<!-- Serif, Sans Serif, Monospace -->

```{r, echo=FALSE}
library(tmap)
data("World")
# ff = c("Times", "Helvetica", "Courier")
ff = c("serif", "sans", "monospace")
tm_shape(World) +
  tm_borders(alpha = 0) +
  tm_credits("serif", fontfamily = "serif", position = c("center", "center"),
             size = 2) +
  tm_credits("sans", fontfamily = "sans", position = c("center", "center"),
             size = 2) +
  tm_credits("monospace", fontfamily = "monospace", position = c("center", "center"),
             size = 2) +
  tm_layout(frame = FALSE)
```

<!-- role of font faces and font families: -->
<!-- - highlight different levels/importance -->
<!-- - distinguish our map from the others (defaults could be boring...) -->

```{r}
library(tmap)
library(sf)
ei_borders = read_sf("data/easter_island/ei_border.gpkg")
ei_points = read_sf("data/easter_island/ei_points.gpkg")
volcanos = subset(ei_points, type == "volcano")
```
<!-- explain defaults -->

```{r, eval=FALSE}
tm_shape(ei_borders) +
  tm_polygons() +
  tm_shape(volcanos) +
  tm_text(text = "name", size = "elevation") +
  tm_credits("Data source: OSM") + 
  tm_layout(main.title = "Volcanos of Easter Island",
            fontface = "italic",
            fontfamily = "serif")
```

```{r, eval=FALSE}
tm_shape(ei_borders) +
  tm_polygons() +
  tm_shape(volcanos) +
  tm_text(text = "name", size = "elevation", fontfamily = "sans") +
  tm_credits("Data source: OSM", fontface = "bold") +
  tm_layout(main.title = "Volcanos of Easter Island",
            main.title.fontface = "bold.italic", 
            legend.title.fontfamily = "monospace")
```

```{r font1, echo=FALSE}
tmt1 = tm_shape(ei_borders) +
  tm_polygons() +
  tm_shape(volcanos) +
  tm_text(text = "name", size = "elevation") +
  tm_credits("Data source: OSM") + 
  tm_layout(main.title = "Volcanos of Easter Island",
            fontface = "italic",
            fontfamily = "serif",
            title.fontface = "plain",
            title.fontfamily = "sans",
            title = "A")
tmt2 = tm_shape(ei_borders) +
  tm_polygons() +
  tm_shape(volcanos) +
  tm_text(text = "name", size = "elevation", fontfamily = "sans") +
  tm_credits("Data source: OSM", fontface = "bold") +
  tm_layout(main.title = "Volcanos of Easter Island",
            main.title.fontface = "bold.italic", 
            legend.title.fontfamily = "monospace",
            title = "B")
tmap_arrange(tmt1, tmt2, nrow = 1)
```


<!-- explain that we can change font faces and families for each element or the whole map -->
<!-- mention size -->

### Font faces

<!-- explain what are font faces -->
<!-- explain when each font face is useful -->
<!-- show how to use them in **tmap** -->

### Font families

<!-- explain what are font families -->
<!-- explain when each font family is useful -->
<!-- show how to use them in **tmap** -->
<!-- build-in fonts only -->

<!-- external fonts with extrafont -->

<!-- external fonts with showtext -->


## Attributes layers

```{r, echo=FALSE}
attr_layers_df = tibble::tribble(
  ~Function, ~Description,
  "tm_grid()", "draws coordinate grid lines of the coordinate system of the main shape object",
  "tm_graticules()", "draws latitude and longitude graticules", 
  "tm_scale_bar()", "adds a scale bar", 
  "tm_compass()", "adds a compass rose", 
  "tm_credits()", "adds a text annotation", 
  "tm_logo()", "adds a logo",
  "tm_xlab()", "adds an x axis labels", 
  "tm_ylab()", "adds an y axis labels",
  "tm_minimap()", "adds minimap in the view mode only"
)
```

\@ref(tab:attr-layers-table)

```{r attr-layers-table, echo=FALSE, warning=FALSE}
library(magrittr)
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
knitr::kable(attr_layers_df, 
             caption = "Attribute layers.",
             caption.short = "Attribute layers.",
             booktabs = TRUE) %>%
  kableExtra::kable_styling("striped",
                            latex_options = "striped", 
                            full_width = FALSE) %>% 
  kableExtra::column_spec(1, bold = TRUE, monospace = TRUE)
```

## Layout element
