--- 
title: "Elegant and informative maps with **tmap**"
author: "Martijn Tennekes, Jakub Nowosad"
date: "`r Sys.Date()`"
description: "This is a book in progress about the tmap package."
knit: bookdown::render_book
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: krantz
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: mtennekes/tmap_book
url: ""
cover-image: ""
colorlinks: yes
graphics: yes
links-as-notes: true
---

```{r index-1, echo=FALSE}
is_on_ghactions = identical(Sys.getenv("GITHUB_ACTIONS"), "true")
is_online = curl::has_internet()
is_html = knitr::is_html_output()
```

```{asis index-2, echo=is_html}
# Welcome {-}
This is the online home of *Elegant and informative maps with **tmap***, a book on geospatial data visualization with the R-package tmap.
```

```{r index-2-2, echo=FALSE, eval=is_html, results="asis"}
if (is_on_ghactions){
    cat(paste0("This version of the book was built on GH Actions on ", Sys.Date(), "."))
} else {
    cat(paste0("This version of the book was built on ", Sys.Date(), "."))
}
```

```{asis index-2-3, echo=is_html}
## How to contribute? {-}
```
